[platformio]
default_envs = cyd_ili9341

[env]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
upload_speed = 460800
monitor_speed = 2000000
lib_deps =
    bodmer/TFT_eSPI@2.5.43
    bodmer/TJpg_Decoder@1.1.0
build_flags =
    -DUSER_SETUP_LOADED
    -DUSE_HSPI_PORT
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DTOUCH_CS=33
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2000000
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4

[env:cyd_ili9341]
build_flags =
    ${env.build_flags}
    -DILI9341_2_DRIVER
    -DPIP_BAUD=2000000

[env:cyd_st7789]
build_flags =
    ${env.build_flags}
    -DST7789_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_INVERSION_OFF
    -DPIP_BAUD=2000000

[env:cyd_ili9341_safe]
build_flags =
    ${env.build_flags}
    -DILI9341_2_DRIVER
    -DPIP_BAUD=921600
    -DPIP_SAFE_LINK=1

[env:cyd_st7789_safe]
build_flags =
    ${env.build_flags}
    -DST7789_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_INVERSION_OFF
    -DPIP_BAUD=921600
    -DPIP_SAFE_LINK=1
